name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip the Lambda function
        run: zip -r lambda_function.zip lambda_function.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name MyLambdaFunction \
            --zip-file fileb://lambda_function.zip
      - name: Get Lambda Function URL
        run: |
          FUNCTION_URL=$(aws lambda get-function-url-config --function-name MyLambdaFunction --query FunctionUrl --output text)
          echo "Lambda Function URL: $FUNCTION_URL"
